### ISSUE TITLE
@everyone ping problem

### ISSUE THREAD

**Issue by Bansku-Dansku** [fabianmakila/WebhookChatLogger#8] opened 2023-12-29 14:03 UTC
So I am using your best plugin WebhookChatLogger, but when people write @everyone on the chat it, the webhook will ping @everyone then. If you can try to make an option for this of fix it to just not ping @everyone.

**Comment by Bansku-Dansku** [comment] 2023-12-29 14:05
![image](https://github.com/fabianmakila/WebhookChatLogger/assets/110292588/279e5423-76df-400e-8026-57a247ddc4ff)
Here is a image of it if  you need.

**Comment by fabianmakila** [comment] 2023-12-29 19:37
As stated [in the wiki](https://github.com/fabianmakila/WebhookChatLogger/wiki/configuration#messagestyle) this is (at the moment at least) working as intended.
![image](https://github.com/fabianmakila/WebhookChatLogger/assets/44451855/524dbece-950b-4dc8-8230-8bc3ff789eb4)

To prevent players from pinging Discord members you can use the other 2 available message styles.

I've planned on rewriting the entire plugin somewhere in the next year and that will most likely "fix" this problem. I'll close this as not planned as stated earlier that this is the current expected behavior of the `MESSAGE` messageStyle.

**Closed by fabianmakila** 2023-12-29 19:37 UTC
